Fixing arity mismatch for ImportUrlJob#send_error
In v2.9.6 of Hyrax we saw the following error:

> File Import Error
>   Error: wrong number of arguments (given 2, expected 1)

It masks other errors, because the message sending for errors is itself
raising an error.

With this change, we ignore all extra parameters and pass the first
parameter.

Related to:

- https://github.com/samvera/hyrax/pull/2821

Resolved in:

- https://github.com/samvera/hyrax/pull/4243
- https://github.com/samvera/hyrax/commit/bfd316e23b5bfbf8d811e8a8dd582c1a2529887b